// scripts/seed.ts
import sharp from 'sharp'
import { promises as fs } from 'fs'
import path from 'path'

const STORAGE_ROOT = process.env.STORAGE_ROOT ?? path.join(process.cwd(), 'storage')
const CAMPAIGN_ID = 'summer-glow-2026'
const ASSET_DIR = path.join(STORAGE_ROOT, 'assets', CAMPAIGN_ID)
const BRIEFS_DIR = path.join(STORAGE_ROOT, 'briefs')

async function makePlaceholder(label: string, color: string, w: number, h: number): Promise<Buffer> {
  const svg = `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg">
    <rect width="${w}" height="${h}" fill="${color}" opacity="0.25"/>
    <rect width="${w}" height="${h}" fill="none" stroke="${color}" stroke-width="6"/>
    <text x="${w/2}" y="${h/2}" font-family="Arial" font-size="${Math.floor(w/15)}" fill="${color}" text-anchor="middle" dominant-baseline="middle" font-weight="bold">${label}</text>
  </svg>`
  return sharp(Buffer.from(svg)).png().toBuffer()
}

async function seed() {
  await fs.mkdir(ASSET_DIR, { recursive: true })
  await fs.mkdir(BRIEFS_DIR, { recursive: true })

  // Radiance SPF 50 hero (reused asset — exists on disk)
  await fs.writeFile(
    path.join(ASSET_DIR, 'radiance-spf50-hero.jpg'),
    await makePlaceholder('Radiance SPF 50', '#4a90d9', 1080, 1080)
  )

  // Packshots
  await fs.writeFile(
    path.join(ASSET_DIR, 'radiance-spf50-pack.png'),
    await makePlaceholder('SPF 50', '#4a90d9', 400, 500)
  )
  await fs.writeFile(
    path.join(ASSET_DIR, 'hydra-serum-pack.png'),
    await makePlaceholder('Hydra Boost', '#7c3aed', 400, 500)
  )

  // Shared logo
  await fs.writeFile(
    path.join(ASSET_DIR, 'lumiere-logo.png'),
    await makePlaceholder('LUMIÈRE', '#111111', 360, 120)
  )

  // No hero for hydra-boost-serum → demonstrates Gemini generation

  // Copy sample brief to storage/briefs/
  const briefSrc = path.join(process.cwd(), 'examples', 'sample-brief.yaml')
  const briefDst = path.join(BRIEFS_DIR, `${CAMPAIGN_ID}.yaml`)
  await fs.copyFile(briefSrc, briefDst)

  console.log('✓ Seeded storage/assets/summer-glow-2026/ with placeholder images')
  console.log('✓ Copied sample brief to storage/briefs/summer-glow-2026.yaml')
  console.log('  → Hydra Boost hero is intentionally absent (will be generated by Gemini or mock)')
}

seed().catch(console.error)
