// scripts/seed.ts
import { promises as fs } from 'fs'
import path from 'path'

const STORAGE_ROOT = process.env.STORAGE_ROOT ?? path.join(process.cwd(), 'storage')
const CAMPAIGN_ID = 'summer-glow-2026'
const ASSET_DIR = path.join(STORAGE_ROOT, 'assets', CAMPAIGN_ID)
const BRIEFS_DIR = path.join(STORAGE_ROOT, 'briefs')
const EXAMPLES_DIR = path.join(process.cwd(), 'examples')

const ASSETS = [
  'radiance-spf50-pack.png',
  'hydra-serum-pack.png',
  'lumiere-logo.png',
]

async function seed() {
  await fs.mkdir(ASSET_DIR, { recursive: true })
  await fs.mkdir(BRIEFS_DIR, { recursive: true })

  // Copy image assets from examples/
  for (const filename of ASSETS) {
    const src = path.join(EXAMPLES_DIR, filename)
    const dst = path.join(ASSET_DIR, filename)
    await fs.copyFile(src, dst)
    console.log(`✓ Copied ${filename}`)
  }

  // Copy sample brief
  await fs.copyFile(
    path.join(EXAMPLES_DIR, 'sample-brief.yaml'),
    path.join(BRIEFS_DIR, `${CAMPAIGN_ID}.yaml`)
  )

  console.log('✓ Copied sample brief to storage/briefs/summer-glow-2026.yaml')
  console.log('  → Hero images are absent — will be generated by OpenAI (or mock placeholder)')
}

seed().catch(console.error)
